### ISSUE TITLE
Add flag/function to check if SSL is supported

### ISSUE THREAD

**Issue by wooky** [pupnp/pupnp#329] opened 2021-07-02 16:41 UTC
Currently, when using the library, there's no way to know if the library was compiled with SSL support. I think it will be useful to have a flag or function that can be accessed at run-time, so the calling program can know if it can use the HTTP client with HTTPS URLs.

**Comment by whyman** [comment] 2021-07-02 21:54
https://github.com/pupnp/pupnp/blob/3c9f59ed33586af26f3736a8769875df68ba706a/upnp/inc/upnpconfig.h.cm#L120

**Comment by wooky** [comment] 2021-07-02 22:03
Sure, that works during compile time, but not during runtime, if you're dynamically linking to the library.

**Comment by whyman** [comment] 2021-07-07 15:40
I probably showing my ignorance here, but If you are dynamically linking and using the SSL symbols, then wouldnt it fail to find those symbols at runtime if they were not present anyway (and therefore not start?)

**Comment by Vollstrecker** [comment] 2021-07-07 15:50
Maybe this is needed if you spread a precompiled binary and don't know what lib is installed on the system. Given it would be easier to link statically or ship the lib with it, but it's not impossible.

Or maybe the distro decides to remove ssl with an update and he want's to tell the user what happend.

**Comment by Vollstrecker** [comment] 2022-01-06 11:36
As there where no more information except the linked issue I just checked the project, the linked language and the irc-channel. The problem is, that the used build-system of the language has no functionality of detecting features of external stuff. It's more or less a more fancy handwritten Makefile based system.

So this issue is more or less an "Let all the others work around the insufficiency of our new fancy stuff" so not our fault, not our problem, not an issue, closing.

**Closed by Vollstrecker** 2022-01-06 11:36 UTC
