### ISSUE TITLE
double "/" cause http server to fail

### ISSUE THREAD

**Issue by bol-van** [pupnp/pupnp#82] opened 2018-07-02 06:03 UTC
I found this problem using gerbera 
https://github.com/gerbera/gerbera/issues/323#issuecomment-401628991

http server coded in libupnp   fail if supplied with multiple "/" on the path
this is critical because offered URLbase include trailing "/" and many clients just append "/something..." and get "//something.."

**Comment by medoc92** [comment] 2018-09-24 09:35
Hi,

libupnp has always rejected these incorrect URLs, this is not a recent change. Could you please list a few of the clients which produce them ?

**Comment by bol-van** [comment] 2018-09-24 09:51
I found this problem using samsung E series TV

**Comment by medoc92** [comment] 2018-09-25 07:19
Please have a look at the discussion in: https://github.com/mrjimenez/pupnp/pull/86

About handling // "correctly": the correct way to handle this according to the RFCs is not to accept them as if there was no double slash :) Apache does accept them, but this is not universal (you can try around on a variety of internet sites as I did).

In any case, the really correct way to address the issue is to not set URLBase which is deprecated by UPnP (since 1.1, which is really the reference version). This is what Gerbera should do, this solves the issue in the best possible way (standard-compliant on both sides).

**Comment by bol-van** [comment] 2018-09-25 07:33
May be. This issue caused me abandon gerbera and move to xupnpd. 
It works fine. Also miniupnpd works fine with sams.
If you're about to fix the problem the best way - its good.
But if you will do nothing - it means gebera will not work with samsung TVs and this fact limits usability

**Comment by medoc92** [comment] 2019-01-15 10:34
Gerbera can fix the issue by not setting URLBase.

I thinj that this issue should be closed.

**Comment by pamapa** [comment] 2020-05-02 15:00
When i try not to set URLBase (done inside pupnp) i get an initialization error (-101 bad parm):

```
	/* non-URL description must have configuration specified */
	if (descriptionType != (enum Upnp_DescType_e)UPNPREG_URL_DESC &&
		!config_baseURL)
		return UPNP_E_INVALID_PARAM;
```

gerbera is using a description string passed inside pupnp:
```
ret = UpnpRegisterRootDevice2(
        UPNPREG_BUF_DESC,
        deviceDescription.c_str(),
        static_cast<size_t>(deviceDescription.length()) + 1,
        true,
        handleUpnpRootDeviceEventCallback,
        this,
        &rootDeviceHandle);
```
When i change `config_baseURL` from true to 0, which should prevent this URLBase appended, i get (-101: UPNP_E_INVALID_PARAM). This error comes from the above pupnp code sniped.

I do not understand that `if`. What is the idea? Is that correct for UPNPREG_BUF_DESC?

**Comment by pamapa** [comment] 2020-05-06 18:54
this double "/" has been fixed with this commit https://github.com/pupnp/pupnp/commit/dc2c54bd710ba9f824c85b8a2a8bd66496767378. I guess we can close this issue.

**Closed** 2020-05-06 21:51 UTC
