### ISSUE TITLE
libupnp-1.8.4在只启动客户端(控制点)时，存在1900、随机端口的全零网段监听[libupnp-1.8.4 when only the client (control point) is started, there is all zero network segment monitoring of 1900, random port]

### ISSUE THREAD

**Issue by LancelotWG** [pupnp/pupnp#170] opened 2020-04-09 09:38 UTC
libupnp的1.8.4版本在仅存在客户端(控制点)时(开启IPv6能力)，有1900、随机端口的udp端口全零网段监听。
问题：
1、这个监听是协议要求吗？
2、如果不是协议要求可以指定IP吗(我理解1900端口的全零监听是必要的，但是随机端口的全零网段监听是必要的吗)？
附件：
** :/home/**  # netstat -anp |awk '{if($4 ~ ":::") print $0;}'
udp6       0      0 :::49528                :::*                                120090/**  
udp6       0      0 :::50911                :::*                                4777/**      
udp6       0      0 :::1900                 :::*                                4777/**
udp6       0      0 :::1900                 :::*                                4777/**
udp6       0      0 :::1900                 :::*                                120090/**
udp6       0      0 :::1900                 :::*                                120090/** 
![image](https://user-images.githubusercontent.com/29793833/78881104-ec7d5880-7a88-11ea-877b-b2fa8173e482.png)
非常感谢开发者们的解答！

(Google Translate):
In version 1.8.4 of libupnp, when only the client (control point) exists (IPv6 capability is enabled), the udp port with 1900 and random ports is monitored on all zero network segments.
problem:
1、 Is this monitoring required by the protocol?
2、 Can IP be specified if not required by the protocol (I understand that all-zero monitoring on port 1900 is necessary, but is all-zero network segment monitoring on random ports necessary)?
annex:
** :/home/**  # netstat -anp |awk '{if($4 ~ ":::") print $0;}'
udp6       0      0 :::49528                :::*                                120090/**  
udp6       0      0 :::50911                :::*                                4777/**      
udp6       0      0 :::1900                 :::*                                4777/**
udp6       0      0 :::1900                 :::*                                4777/**
udp6       0      0 :::1900                 :::*                                120090/**
udp6       0      0 :::1900                 :::*                                120090/** 
![image](https://user-images.githubusercontent.com/29793833/78881104-ec7d5880-7a88-11ea-877b-b2fa8173e482.png)
Thank you very much for your answers!

**Comment by LancelotWG** [comment] 2020-04-09 09:39
** :/home/**  # netstat -anp |awk '{if($4 ~ ":::") print $0;}'
udp6       0      0 :::49528                :::*                                120090/**  
udp6       0      0 :::50911                :::*                                4777/**  
udp6       0      0 :::547                  :::*                                127268/dhcpd        
udp6       0      0 :::1900                 :::*                                4777/**  
udp6       0      0 :::1900                 :::*                                4777/**  
udp6       0      0 :::1900                 :::*                                120090/**  
udp6       0      0 :::1900                 :::*                                120090/** 
udp6       0      0 :::4789                 :::*                                -

**Comment by elgorro** [comment] 2020-05-03 06:45
I'm using [Gerbera.io UPnP](https://github.com/gerbera/gerbera) and also issuing this kind of problem and I found this closed issue on the Gerbera [backlog](https://github.com/gerbera/gerbera/issues/266):

- As I need a firewall in my private network on my pc it's states also kind one "random" port always, its very unconfortable-ish to open the port always manually.
- The [Firewall GUI](https://github.com/costales/gufw) somehow displays this Random-Port is from [Avahi](http://avahi.org/) - but also an static port 5353...
- In the [Arch Forom](https://wiki.archlinux.org/index.php/Avahi) I read about configuring and it also has a [bug with IPv6](https://wiki.archlinux.org/index.php/Avahi#Hostname_changes_with_appending_incrementing_numbers)

So my expected behavior would be to bind this necessary port somehow, but I don't know which project is responsible and how to do it. Do I need to turn off IPv6 or to create a avahi-service manually or is it something hidden in a codebase?

@mrjimenez May you can help clearify?

**Comment by elgorro** [comment] 2020-05-22 10:01
For me I solved with disabling (old) Avahi-Daemon (service and socket off) and enabling [Systemd-Resolved](https://wiki.archlinux.org/index.php/Systemd-resolved#mDNS) on. Hope this helps!

**Comment by mrjimenez** [comment] 2020-05-22 11:28
Hi elgorro,

Thanks for your report, it sure does help.

**Comment by LancelotWG** [comment] 2020-08-06 03:54
该问题通过给1900绑定指定IP，以及禁止create_ssdp_sock_v6和create_ssdp_sock_v6_ula_gua解决

**Comment by Vollstrecker** [comment] 2022-01-06 12:50
So is this still an issue, or a config problem on the client? Should this stay open

**Comment by elgorro** [comment] 2022-02-10 16:59
Would need actually some testing, according to [Avahi#254](https://github.com/lathiat/avahi/issues/254) it's by design. I'm still not sure why pupnp or gerbera using it - in terms of need to opening the random port - to work or why it must be a random port!?!

**Comment by elgorro** [comment] 2022-02-18 08:29
I guess it can be closed, regarding to [this answer from Avahi](https://github.com/lathiat/avahi/issues/254#issuecomment-1042920714) i's necessary to have this spare and random port open (beside mDNS), but for outgoing connections only. I've also tried with my current setup and it's working now out of the box - so my inital problem was another (but is gone). I hope this helps.

**Comment by Vollstrecker** [comment] 2022-02-18 08:41
Closing issues always helps.

**Closed by Vollstrecker** 2022-02-18 08:41 UTC
