### ISSUE TITLE
Version 1.6.25 has no pdfs in docs/dist which breaks the build

### ISSUE THREAD

**Issue by yurivict** [pupnp/pupnp#72] opened 2018-03-15 07:57 UTC
The build breaks:
```
Making all in docs/dist
make[4]: make[4]: don't know how to make ./UPnP_Programming_Guide.pdf. Stop
```

**Comment by ukleinek** [comment] 2018-03-15 08:01
Which revision and which command did you use to build?

**Comment by yurivict** [comment] 2018-03-15 08:07
configured with ```--with-documentation=```, and ran gmake. This is in the FreeBSD port.
pdf files were present in 1.6.22, now they aren't present in 1.6.25.

**Comment by ukleinek** [comment] 2018-03-15 08:24
ok, can reproduce. Just dropping the two removed pdfs doesn't fix that target though, now it fails for me with 

    /usr/bin/install: will not overwrite just-created '/tmp/lala/tmp/tralala/examples/sample_util.c' with 'common/sample_util.c'
    /usr/bin/install: will not overwrite just-created '/tmp/lala/tmp/tralala/examples/sample_util.h' with 'common/sample_util.h'

The problem is that these files are included via tv_ctrlpt_SOURCES and tv_device_SOURCES twice in examples_DATA I think. Don't see a quick way to fix that. I also wonder if tv_combo_SOURCES should be included in examples_DATA.

**Comment by ffontaine** [comment] 2018-03-15 16:09
@ukleinek did you relaunch a configure after removing those files from Makefile.am? On my side, it's working. Can you retest with branch-1.6.x?

**Comment by ukleinek** [comment] 2018-03-15 20:36
@ffontaine: The problem happens when building with --with-documentation for me. See https://gist.github.com/ukleinek/d438c4e3584e366598221a31a905767c

**Comment by ffontaine** [comment] 2018-03-15 21:43
OK thanks @ukleinek, I got the same error, I was not running make install. This is strange that we didn't notice this issue before as upnp/sample/Makefile.am hasn't be updated since July 2013 ... This error was already present in 1.6.22 ...

IMHO, I would delete examplesdir an examples_DATA from this file. These files are not documentation but source and header files of our examples. But I will let @mrjimenez give his opinion on that.

**Comment by yurivict** [comment] 2018-03-15 21:50
> This is strange that we didn't notice this issue before as upnp/sample/Makefile.am hasn't be updated since July 2013 ... This error was already present in 1.6.22 ...

1.6.22 builds fine. SourceForge shows high downloads count of 1.6.22, and low for 1.6.25. They either couldn't narrow the problem, or didn't care to report it.

**Comment by ffontaine** [comment] 2018-03-15 22:12
I got the same error than @ukleinek on 1.6.22 from github tar.gz and sourceforge tar.bz2 when building and **installing** with "--with-documentation" ... 
I think that most of the users keep the default value and does not use the --with-documentation flag.

**Comment by mrjimenez** [comment] 2018-03-15 23:56
I agree with Fabrice, these files don't need to be in the tarball, even more today when we have git.

As always, patches are welcome :)

**Comment by ffontaine** [comment] 2018-03-16 06:25
OK, I fixed the issue on branch-1.6.x and branch-1.8.x. @mrjimenez can you release 1.6.26 and 1.8.4?

**Comment by ukleinek** [comment] 2018-03-16 06:35
There is some magic you could have added to the commit log to make it automatically close this issue.
https://help.github.com/articles/closing-issues-using-keywords/

**Comment by ukleinek** [comment] 2018-03-16 07:42
@mrjimenez: I have a few cleanups pending, can you please wait a bit before cutting a new set of releases?

**Comment by mrjimenez** [comment] 2018-03-16 15:42
@ukleinek , I see no reason to hurry. Take your time.

**Comment by Vollstrecker** [comment] 2021-02-15 09:02
Obviously this should be closed already

**Closed** 2021-02-22 00:30 UTC
