### ISSUE TITLE
1.14.8 downgrades the .so version from 17 to 16

### ISSUE THREAD

**Issue by dvzrv** [pupnp/pupnp#336] opened 2021-08-08 17:01 UTC
Hi! I'm packaging libupnp for Arch Linux.

Upon trying to package 1.14.8 (coming from 1.14.7) I realized that this version attempts to *downgrade* the .so version for libupnp from 17 to 16 when using the autotools based setup.

```
usr/lib/libupnp.so.17 -> usr/lib/libupnp.so.16
usr/lib/libupnp.so.17.0.7 -> usr/lib/libupnp.so.16.1.8
```

**Comment by dvzrv** [comment] 2021-08-08 17:05
FWIW this is not the case if I switch to the cmake setup. However, as it seems the autotools setup still counts as supported it's probably worth fixing this.

**Comment by mrjimenez** [comment] 2021-08-08 17:27
Hi David,

My fault. I have increased the "age" but forgot to increase the "current".

Thank you for reporting. I will hopefully fix it today and release a 1.14.9.

Regards,
Marcelo.

**Comment by dvzrv** [comment] 2021-08-09 20:50
Just to ensure this is all correct:

The patch level release 1.14.9 now increases the .so version from 17 to 18 (when using the cmake setup). Was this the desired outcome?

**Comment by dvzrv** [comment] 2021-08-09 20:58
This is not the case when building with autotools:

```
usr/lib/libixml.so.11.1.0 -> usr/lib/libixml.so.11.0.1
usr/lib/libupnp.so.17.8.1 -> usr/lib/libupnp.so.17.1.0
```

Versus when building with cmake:

```
usr/lib/libupnp.so.17 -> usr/lib/libupnp.so.18
usr/lib/libupnp.so.17.8.1 -> usr/lib/libupnp.so.18.0.1
```

**Comment by dvzrv** [comment] 2021-08-09 21:01
but I just noticed that using the autotools setup for 1.14.9 (in either case coming from 1.14.8) downgrades the .so version for both libixml.so and libupnp.so.

Meanwhile for the upgrade from 1.14.7 (autotools) to 1.14.8 (cmake) and from 1.14.8 to 1.14.9 (both cmake) no change for libixml.so was registered.

**Comment by mrjimenez** [comment] 2021-08-09 21:04
No. It looks like CMake is doing the naive interpretation of libtool numbers. 

@Vollstrecker , could you please take a look? .so version must be "current" minus "age"

**Comment by mrjimenez** [comment] 2021-08-09 21:12
> but I just noticed that using the autotools setup for 1.14.9 (in either case coming from 1.14.8) downgrades the .so version for both libixml.so and libupnp.so.
> 
> Meanwhile for the upgrade from 1.14.7 (autotools) to 1.14.8 (cmake) and from 1.14.8 to 1.14.9 (both cmake) no change for libixml.so was registered.

Ok, there is some confusion. Lets skip 1.14.8 and pretend it never existed :laughing: It is odd that libixml is changing its numbers. The last change in ixml was in 1.14.5 when the revision was incremented to 1. Since then LT_VERSION_IXML has been 11:1:0 (current:revision:age).

**Comment by Vollstrecker** [comment] 2021-08-10 05:09
I thought I did that already. And I wondered why it worked, as they should all die the same.

I'm back home at thursday, then this will be done, again.

**Comment by Vollstrecker** [comment] 2021-08-10 11:30
I can currently only check from my phone, but it seems the release tagged branch hasn't the cmake-dir include. The fix for the version handling was part of that split. Could someone confirm this?

**Comment by mrjimenez** [comment] 2021-08-10 12:31
Hi @Vollstrecker , take it easy, no hurry, we can wait until you're back.

Maybe we only have the right config in master and we forgot to backport it to 1.14.

**Comment by Vollstrecker** [comment] 2021-08-13 09:58
It's d341a10 that's added the right calculation and 6aff4c7 that fixed the links numbering. See cmake/autoheader.cmake lines 56 and 61 that does the trick.

**Comment by dvzrv** [comment] 2021-08-19 19:47
With 1.14.10 (upgrading from 1.14.8, built using cmake) I get:

autotools:

```
usr/lib/libixml.so.11.1.0 -> usr/lib/libixml.so.11.0.1
usr/lib/libupnp.so.17.8.1 -> usr/lib/libupnp.so.17.1.1
```

cmake

```
usr/lib/libixml.so.11.1.0 -> usr/lib/libixml.so.11.0.1
usr/lib/libupnp.so.17.8.1 -> usr/lib/libupnp.so.17.1.1
```

Apart from both still downgrading the .so version, when built with cmake our tooling also reports a soname change:

```
libixml.so=11-64 -> libixml.so=11.0.1-64
libupnp.so=17-64 -> libupnp.so=17.1.1-64
```

This is because:

```
lrwxrwxrwx root/root         0 2021-08-19 21:44 usr/lib/libixml.so -> libixml.so.11.0.1
-rwxr-xr-x root/root     56336 2021-08-19 21:44 usr/lib/libixml.so.11
lrwxrwxrwx root/root         0 2021-08-19 21:44 usr/lib/libixml.so.11.0.1 -> libixml.so.11
lrwxrwxrwx root/root         0 2021-08-19 21:44 usr/lib/libupnp.so -> libupnp.so.17.1.1
-rwxr-xr-x root/root    265504 2021-08-19 21:44 usr/lib/libupnp.so.17
lrwxrwxrwx root/root         0 2021-08-19 21:44 usr/lib/libupnp.so.17.1.1 -> libupnp.so.17
```

Sorry, but 1.14.10 is also broken :-/

**Comment by mrjimenez** [comment] 2021-08-20 01:50
Hi David,

I think I am getting different results. Just built these four releases and summarized in the tables below.

For libupnp:

| Release | autotools         | cmake             |
|---------|-------------------|-------------------|
| 1.14.7  | libupnp.so.17.0.7 | libupnp.so.17.7.0 |
| 1.14.8  | libupnp.so.16.1.8 | libupnp.so.17.8.1 |
| 1.14.9  | libupnp.so.17.1.0 | libupnp.so.18.0.1 |
| 1.14.10 | libupnp.so.17.1.1 | libupnp.so.17.1.1 |

For libixml:

| Release | autotools         | cmake             |
|---------|-------------------|-------------------|
| 1.14.7  | libixml.so.11.0.1 | libixml.so.11.1.0 |
| 1.14.8  | libixml.so.11.0.1 | libixml.so.11.1.0 |
| 1.14.9  | libixml.so.11.0.1 | libixml.so.11.1.0 |
| 1.14.10 | libixml.so.11.0.1 | libixml.so.11.0.1 |

From these results, both autotools and cmake are doing the right thing now.

- libupnp autotools was buggy in 1.14.8
- libupnp cmake got right in 1.14.10
- ixml autotools has always been right
- ixml cmake got right in 1.14.10

**Comment by Vollstrecker** [comment] 2021-08-20 07:02
Nice, I just wanted to start the same. libixml.so=11-64 -> libixml.so=11.0.1-64 is a interesting line, as it seems the tools tell us the installed symlink, which would be correct and hasn't changed (at least not intended). Beside the -64 I can't see anything unusual, but as this toolset seems to be used for packaging by a whole distro, I'm sure this want's to tell us more than I can read from it.

But from your table, the proplem is still there. As the report was for 1.14.8, I guess the old version packaged was 1.14.7. If cmake was used for that, the name changes from 17.7.0 to 17.1.1 which really is a downgrade that isn't wanted. The only solution I see to sort out this mess would be to release with a jump to 17.7.1 or 17.8.0.

**Comment by dvzrv** [comment] 2021-08-20 07:36
At any rate, this for example is not correct (see [my last comment](https://github.com/pupnp/pupnp/issues/336#issuecomment-902194178)):

```
lrwxrwxrwx root/root         0 2021-08-19 21:44 usr/lib/libixml.so -> libixml.so.11.0.1
```

In symlink terms it needs to be `libixml.so` -> `libixml.so.11` -> `libixml.so.11.0.1`.
With `libixml.so` -> `libixml.so.11.0.1` this introduces a soname bump on *every* minor version update of the lib version. This would require downstreams to rebuild every package against the updated version of these shared objects.

In regards to the (minor) version downgrade of the .so: If you are fine with that and I don't need a rebuild because of that, then I'm okay with it (although it is of course not overly pretty ;-) ).

**Comment by Vollstrecker** [comment] 2021-08-20 12:40
I just pushed a new branch called link-switch. I can't check what version get's compiled into the lib itself now, but it should fix the links. Can you test what happens with that one?

@mrjimenez This one was based on master, but I'm sure you'll be able to port it to the release (sorry I'm drowning in reallifework atm.)

**Comment by mrjimenez** [comment] 2021-08-20 14:04
Hi David,

Maybe I am not accurately understanding what you say. Please do notice that I am new to the CMake thing and libupnp has always used autotools. Vollstrecker has done a great job bringing CMake into libupnp, but the whole thing is relatively recent.

For autotools:

```bash
$ ls -la ./upnp/.libs/libupnp.so*      
lrwxrwxrwx 1 mroberto users     17 ago 19 22:40 ./upnp/.libs/libupnp.so -> libupnp.so.17.1.1
lrwxrwxrwx 1 mroberto users     17 ago 19 22:40 ./upnp/.libs/libupnp.so.17 -> libupnp.so.17.1.1
-rwxr-xr-x 1 mroberto users 725456 ago 19 22:40 ./upnp/.libs/libupnp.so.17.1.1
-rwxr-xr-x 1 mroberto users 725456 ago 19 22:40 ./upnp/.libs/libupnp.so.17.1.1T
$ ls -la ./ixml/.libs/libixml.so* 
lrwxrwxrwx 1 mroberto users     17 ago 19 22:40 ./ixml/.libs/libixml.so -> libixml.so.11.0.1
lrwxrwxrwx 1 mroberto users     17 ago 19 22:40 ./ixml/.libs/libixml.so.11 -> libixml.so.11.0.1
-rwxr-xr-x 1 mroberto users 140376 ago 19 22:40 ./ixml/.libs/libixml.so.11.0.1
```

For CMake:

```bash
$ ls -la ./build/upnp/libupnp.so*                       
lrwxrwxrwx 1 mroberto users     17 ago 19 22:40 ./build/upnp/libupnp.so -> libupnp.so.17.1.1
-rwxr-xr-x 1 mroberto users 770256 ago 19 22:40 ./build/upnp/libupnp.so.17
lrwxrwxrwx 1 mroberto users     13 ago 19 22:40 ./build/upnp/libupnp.so.17.1.1 -> libupnp.so.17
$ ls -la ./build/ixml/libixml.so* 
lrwxrwxrwx 1 mroberto users     17 ago 19 22:40 ./build/ixml/libixml.so -> libixml.so.11.0.1
-rwxr-xr-x 1 mroberto users 141544 ago 19 22:40 ./build/ixml/libixml.so.11
lrwxrwxrwx 1 mroberto users     13 ago 19 22:40 ./build/ixml/libixml.so.11.0.1 -> libixml.so.11
```

Notice that these symlinks are generated by the build system itself, i.e., llbtool in the case of autotools or cmake.

I can see that Autotools and CMake do not agree upon who is the real file and who is the symlink. And they also do not agree with the scheeme you proposed.

I also fail to understand the soname bump issue, since from a file access point of view, accessing the file or the symlink makes no difference.

So lets dive a little bit deeper into the rabbit hole:

```bash
# autotools
$ readelf -a ./ixml/.libs/libixml.so | grep SONAME
 0x000000000000000e (SONAME)             Library soname: [libixml.so.11]
# cmake
$ readelf -a ./build/ixml/libixml.so | grep SONAME                       
 0x000000000000000e (SONAME)             Library soname: [libixml.so.11.0.1]
```

As you can see, the Autotools generated version of the file has a soname that only includes what we could call the major version. The CMake version includes both the minor version, which basically is irrelevant from the compatibility standpoint (old software should link as long as the major is the same) and the "patch" or "revision" number which is even more irrelevant, since it basically means "bug fixes". I think that this is the reason why Autotools uses just the major, which in libtools terms is "current" minus "age".

Please correct me if I am wrong, but it seems to me that if you are using a CMake build, indeed you have a soname bump, but if you are using Autotools, this is not the case.

If the previous paragraph is correct, maybe @Vollstrecker still has an issue to take care (no hurries, man! I still did not check your last pull request).

**Comment by Vollstrecker** [comment] 2021-08-20 14:14
In the branch I just switched The fields where MAJOR or MAJOR.MINOR.PATCH are saved. If the soname compiled in is like you wrote, then I would make a strong guess that this will be the same after this switch.

According to man ldconfig libfoo.so -> libfoo.so.1 -> libfoo.so.1.12 is the right ordering, so in this case and the the variant autotools is doing, the real lib would be libupnp.so.17.1.1. The switch I made now should reproduce exactly this also, so we would be in the state what at least one programm directly working with these things is suggesting (man ldd and man ld.so don't say anything about this) which is in my eyes the best we can achieve.

**Comment by dvzrv** [comment] 2021-08-20 16:54
> Maybe I am not accurately understanding what you say. Please do notice that I am new to the CMake thing and libupnp has always used autotools. Vollstrecker has done a great job bringing CMake into libupnp, but the whole thing is relatively recent.
> 
> For autotools:
> 
> ```shell
> $ ls -la ./upnp/.libs/libupnp.so*      
> lrwxrwxrwx 1 mroberto users     17 ago 19 22:40 ./upnp/.libs/libupnp.so -> libupnp.so.17.1.1
> lrwxrwxrwx 1 mroberto users     17 ago 19 22:40 ./upnp/.libs/libupnp.so.17 -> libupnp.so.17.1.1
> -rwxr-xr-x 1 mroberto users 725456 ago 19 22:40 ./upnp/.libs/libupnp.so.17.1.1
> -rwxr-xr-x 1 mroberto users 725456 ago 19 22:40 ./upnp/.libs/libupnp.so.17.1.1T
> $ ls -la ./ixml/.libs/libixml.so* 
> lrwxrwxrwx 1 mroberto users     17 ago 19 22:40 ./ixml/.libs/libixml.so -> libixml.so.11.0.1
> lrwxrwxrwx 1 mroberto users     17 ago 19 22:40 ./ixml/.libs/libixml.so.11 -> libixml.so.11.0.1
> -rwxr-xr-x 1 mroberto users 140376 ago 19 22:40 ./ixml/.libs/libixml.so.11.0.1
> ```

This is good with 0.14.10 and something I can switch (back) to.

> For CMake:
> 
> ```shell
> $ ls -la ./build/upnp/libupnp.so*                       
> lrwxrwxrwx 1 mroberto users     17 ago 19 22:40 ./build/upnp/libupnp.so -> libupnp.so.17.1.1
> -rwxr-xr-x 1 mroberto users 770256 ago 19 22:40 ./build/upnp/libupnp.so.17
> lrwxrwxrwx 1 mroberto users     13 ago 19 22:40 ./build/upnp/libupnp.so.17.1.1 -> libupnp.so.17
> $ ls -la ./build/ixml/libixml.so* 
> lrwxrwxrwx 1 mroberto users     17 ago 19 22:40 ./build/ixml/libixml.so -> libixml.so.11.0.1
> -rwxr-xr-x 1 mroberto users 141544 ago 19 22:40 ./build/ixml/libixml.so.11
> lrwxrwxrwx 1 mroberto users     13 ago 19 22:40 ./build/ixml/libixml.so.11.0.1 -> libixml.so.11
> ```

Here we have the issue, that - if packaged as is - other applications linking against e.g. libixml.so.11 would break (i.e. require rebuild).

> Please correct me if I am wrong, but it seems to me that if you are using a CMake build, indeed you have a soname bump, but if you are using Autotools, this is not the case.

Correct! :)

The downgrade of the "actual" lib file ([as shown in your earlier comment](https://github.com/pupnp/pupnp/issues/336#issuecomment-902368689)) is not a problem, but it would of course be more pretty to pull up the minor version above the version that was introduced (accidentally) in between. This is really up to you though, of course!

> In the branch I just switched The fields where MAJOR or MAJOR.MINOR.PATCH are saved. If the soname compiled in is like you wrote, then I would make a strong guess that this will be the same after this switch.
> 
> According to man ldconfig libfoo.so -> libfoo.so.1 -> libfoo.so.1.12 is the right ordering, so in this case and the the variant autotools is doing, the real lib would be libupnp.so.17.1.1. The switch I made now should reproduce exactly this also, so we would be in the state what at least one programm directly working with these things is suggesting (man ldd and man ld.so don't say anything about this) which is in my eyes the best we can achieve.

@Vollstrecker I can try this later, but am nearly on holidays now. I will switch back to the autotools setup for the time being I think.
Many thanks for looking into this and don't stress about it, as this ticket at least exists in case anyone is running into issues with the setup in the meantime.

**Comment by mrjimenez** [comment] 2021-08-20 18:49
> The downgrade of the "actual" lib file ([as shown in your earlier comment](https://github.com/pupnp/pupnp/issues/336#issuecomment-902368689)) is not a problem, but it would of course be more pretty to pull up the minor version above the version that was introduced (accidentally) in between. This is really up to you though, of course!

Not a problem at all.

See if you agree with me, for 1.14.11, both cmake and autotools:

lib | libname | soname
---|---|---
upnp | libupnp.so.17.1.2 | libupnp.so.17
ixml | libixml.so.11.1.1 | libixml.so.11

@dvzrv If you agree, we have a new release.

@Vollstrecker , your patch works fine, just backported it. Thanks!

**Comment by whyman** [comment] 2021-08-29 12:11
I also notice that the versions in the `upnpconfig.h` are wrong (on my arch install with 1.14.8)

```cpp
/** The library version (string) e.g. "1.3.0" */
#define UPNP_VERSION_STRING "17.8.1"

/** Major version of the library */
#define UPNP_VERSION_MAJOR 17

/** Minor version of the library */
#define UPNP_VERSION_MINOR 8
```

**Comment by whyman** [comment] 2021-08-29 12:19
This means in Gerbera for example we see in CMake:

```-- Found libupnp: /usr/lib/libupnp.so (found version 17.8.1)
CMake Warning at CMakeLists.txt:378 (message):
      !! It is strongly recommended to build libupnp with --enable-reuseaddr !!
      Without this option Gerbera will be unable to restart with the same port number.


CMake Warning at CMakeLists.txt:385 (message):
      !! It is strongly recommended to build libupnp with --disable-blocking-tcp-connections !!
      Without this option non-responsive control points can cause libupnp to hang.
```

And our version checks no longer work as expected

**Comment by mrjimenez** [comment] 2021-08-29 22:04
> I also notice that the versions in the `upnpconfig.h` are wrong (on my arch install with 1.14.8)
> 
> ```c++
> /** The library version (string) e.g. "1.3.0" */
> #define UPNP_VERSION_STRING "17.8.1"
> 
> /** Major version of the library */
> #define UPNP_VERSION_MAJOR 17
> 
> /** Minor version of the library */
> #define UPNP_VERSION_MINOR 8
> ```
> 
> These have been the "user facing" release numbers previously.

This seems wrong.

**Comment by Vollstrecker** [comment] 2021-09-19 11:04
Sorry for the delay, I wanted to fix this the evening after the report but totally forgot about it.
And I forgot something in there but can't just roll back (nice action for my first direct commit, chame on me).

**Comment by Vollstrecker** [comment] 2021-09-19 12:07
I changed the source now to have the right version in the right vars. I made the mistake in adding new vars for the calculated version after I was told that they are calculated and then the confusion on which var to use at the different locations started. Now all the varnames are as they should be, the export has the versions of the libs instead of the release and (hopefully) all confusions are gone.

The last 3 commits should be pickable to the release branch if all agree.

**Comment by mrjimenez** [comment] 2021-09-19 20:29
> Sorry for the delay, I wanted to fix this the evening after the report but totally forgot about it.
> And I forgot something in there but can't just roll back (nice action for my first direct commit, chame on me).

Don't worry about that, just fix it, no one will say anything :smile: 

> I changed the source now to have the right version in the right vars. I made the mistake in adding new vars for the calculated version after I was told that they are calculated and then the confusion on which var to use at the different locations started. Now all the varnames are as they should be, the export has the versions of the libs instead of the release and (hopefully) all confusions are gone.

Great!

**Comment by mrjimenez** [comment] 2021-09-19 20:33
> The last 3 commits should be pickable to the release branch if all agree.

OK, last 3, I'll pick them.

**Comment by mrjimenez** [comment] 2021-09-19 20:50
Hi @Vollstrecker ,

I am failing to pick "Fixed (hopefully) the last remainder of the wrong version calculation.  Affects: #336" e52138a420ccfd7ab9ae65b290638487e560f9f0, likely because we don't have cmake/autoheader.cmake in the release branch. Maybe it is better if you do the picking, what do you think? Otherwise I might keep bothering you with this kind of detail.

**Comment by Vollstrecker** [comment] 2021-09-19 21:45
Damned, I always forget that the release branch was synced before the files were split. Unfortunately I'm on the road again. I'll fix this on Wednesday.

**Comment by mrjimenez** [comment] 2021-09-19 23:01
No problem, man.

**Comment by Vollstrecker** [comment] 2021-09-24 21:35
k, I'm done backporting this, just wanted to double check: readelf now reports libupnp.so.17 as soname. Built with autotools the installed thing is 

```libupnp.so -> libupnp.so.17.1.2 and libupnp.so.17 -> libupnp.so.17.1.2```

while with cmake it's 

```libupnp.so -> libupnp.so.17 and libupnp.so.17 -> libupnp.so.17.1.2```

so in both case the real lib is the one with the whole number, soname is just the major version. I guess usually linking happens to the soname-file, so they are both the same. From my view, even if just libupnp.so is used the end is the same.

So if the little difference in the installed symlinks doesn't cause any problems, I can commit any time.

**Comment by mrjimenez** [comment] 2021-09-24 23:50
Looks ok to me, go ahead!

**Comment by Vollstrecker** [comment] 2021-09-25 09:29
Done, as I have this repo and my fork in just one local repo (I have to overthink this some day) I'm almost sure nothing was lost on the way.

**Comment by dvzrv** [comment] 2021-09-25 11:47
> k, I'm done backporting this, just wanted to double check: readelf now reports libupnp.so.17 as soname. Built with autotools the installed thing is
> 
> `libupnp.so -> libupnp.so.17.1.2 and libupnp.so.17 -> libupnp.so.17.1.2`
> 

This does not look right though (is it a typo?).
The symlinks should be the same as with the cmake setup below.
If the top-most symlink (`libupnp.so`) points at the specific .so version (17.1.2) a rebuild is required on each patch level version update of the .so.

> while with cmake it's
> 
> `libupnp.so -> libupnp.so.17 and libupnp.so.17 -> libupnp.so.17.1.2`
> 
> so in both case the real lib is the one with the whole number, soname is just the major version. I guess usually linking happens to the soname-file, so they are both the same. From my view, even if just libupnp.so is used the end is the same.

**Comment by mrjimenez** [comment] 2021-09-25 11:48
Hi @Vollstrecker ,

Sorry, but I think it is still not ok, look:

```diff
$ diff -u ./upnp/inc/upnpconfig.h ./build/upnp/inc/upnpconfig.h
--- ./upnp/inc/upnpconfig.h     2021-09-25 08:41:47.231036080 -0300
+++ ./build/upnp/inc/upnpconfig.h       2021-09-25 08:40:47.592729796 -0300
@@ -1,4 +1,3 @@
-/* upnp/inc/upnpconfig.h.  Generated from upnpconfig.h.in by configure.  */
 /* -*- C -*- */
 /*******************************************************************************
  *
@@ -39,16 +38,22 @@
  ***************************************************************************/
 
 /** The library version (string) e.g. "1.3.0" */
-#define UPNP_VERSION_STRING "1.14.11"
+#define UPNP_VERSION_STRING "17.1.2"
 
 /** Major version of the library */
-#define UPNP_VERSION_MAJOR 1
+#define UPNP_VERSION_MAJOR 17
 
 /** Minor version of the library */
-#define UPNP_VERSION_MINOR 14
+#define UPNP_VERSION_MINOR 1
+#ifndef UPNP_VERSION_MINOR
+#      define UPNP_VERSION_MINOR 0
+#endif
 
 /** Patch version of the library */
-#define UPNP_VERSION_PATCH 11
+#define UPNP_VERSION_PATCH 2
+#ifndef UPNP_VERSION_PATCH
+#      define UPNP_VERSION_PATCH 0
+#endif
 
 /** The library version (numeric) e.g. 10300 means version 1.3.0 */
 #define UPNP_VERSION \
```

**Comment by mrjimenez** [comment] 2021-09-25 12:32
Hi @dvzrv ,

> > k, I'm done backporting this, just wanted to double check: readelf now reports libupnp.so.17 as soname. Built with autotools the installed thing is
> > `libupnp.so -> libupnp.so.17.1.2 and libupnp.so.17 -> libupnp.so.17.1.2`
> 
> This does not look right though (is it a typo?).
> The symlinks should be the same as with the cmake setup below.
> If the top-most symlink (`libupnp.so`) points at the specific .so version (17.1.2) a rebuild is required on each patch level version update of the .so.
> 
> > while with cmake it's
> > `libupnp.so -> libupnp.so.17 and libupnp.so.17 -> libupnp.so.17.1.2`
> > so in both case the real lib is the one with the whole number, soname is just the major version. I guess usually linking happens to the soname-file, so they are both the same. From my view, even if just libupnp.so is used the end is the same.

With the last committed version I have:

```bash
# autotools
$ ls -la ./upnp/.libs/libupnp.so* 
lrwxrwxrwx 1 mroberto users     17 set 25 08:41 ./upnp/.libs/libupnp.so -> libupnp.so.17.1.2
lrwxrwxrwx 1 mroberto users     17 set 25 08:41 ./upnp/.libs/libupnp.so.17 -> libupnp.so.17.1.2
-rwxr-xr-x 1 mroberto users 725456 set 25 08:41 ./upnp/.libs/libupnp.so.17.1.2
-rwxr-xr-x 1 mroberto users 725456 set 25 08:41 ./upnp/.libs/libupnp.so.17.1.2T

#cmake
$ ls -la ./build/upnp/libupnp.so*
lrwxrwxrwx 1 mroberto users     13 set 25 08:40 ./build/upnp/libupnp.so -> libupnp.so.17
lrwxrwxrwx 1 mroberto users     17 set 25 08:40 ./build/upnp/libupnp.so.17 -> libupnp.so.17.1.2
-rwxr-xr-x 1 mroberto users 770256 set 25 08:40 ./build/upnp/libupnp.so.17.1.2
```

I don't think we have ever modified the autotools generated scheeme. I don't know if it is even possible to change that.

> If the top-most symlink (`libupnp.so`) points at the specific .so version (17.1.2) a rebuild is required on each patch level version update of the .so.

I don't think it has to do with the symlinks. Shouldn't the linker be worried about the soname? Sonames now look right here:

```bash
$ readelf -a ./upnp/.libs/libupnp.so | grep SONAME
 0x000000000000000e (SONAME)             Library soname: [libupnp.so.17]

$ readelf -a ./build/upnp/libupnp.so | grep SONAME
 0x000000000000000e (SONAME)             Library soname: [libupnp.so.17]
```

I am not sure I am understanding correctly what you are saying. We are talking about dynamic links, right? Statically linked programs have an issue only when you deliberately relink them, which is something you should probably do on a new distro release. The dynamic linker has to do its job and "link" every time the program is ran. "Link" means to load the necessary libraries in memory, resolve the symbols and do the necessary fixes to the program's calling addresses. Only the soname should matter and this is a field inside the ELF files. Please correct me, I still don't see why the link order matters.

Best regards,
Marcelo.

**Comment by Vollstrecker** [comment] 2021-09-25 12:40
I thought the version of the lib is supposed to show up in the header? 1.14.11 is the release of the package (upnp and ixml) and 1.17.2 is the upnp version because this is what the lib itself reports. So the header should show 1.14.11? The question is also what version to write into the config for cmake, as the last change made it possible to search for upnp 1.17.1 and ixml 11.1.1. If I change that to 1.14.11 for upnp, should imxl have the same version? Doesn't seem consistent to me.

> I don't think we have ever modified the autotools generated scheeme. I don't know if it is even possible to change that.

Same for cmake. I guess it's possible to manipulate this by hand with not little effort.

**Comment by Vollstrecker** [comment] 2021-09-25 13:34
I took a short look, and if I'm right it's getting interresting. pupnp_version is 1.14.x and upnp_version is 17.x.x. Both get read from configure.ac, upnp_version needs to be set as soname and pupnp_version needs to be written into upnp_config.h, so far so doable. From configure.ac the values for autoconfig.h are read and transported also automatically and there define UPNP_VERSION needs to be substituted with pupnp_version.

I guess this will be more than hard to read when done. Have you ever thought about splitting ixml and upnp into separate packages, both with their own version that's the same over the whole thing?

**Comment by Vollstrecker** [comment] 2021-09-25 14:34
Done(?) again.

Now the soname reports 17.x.x but find_package in cmake and the headers will show 1.14.x.

**Comment by Vollstrecker** [comment] 2021-09-25 14:37
And now the pkgconfig does the same.

**Comment by dvzrv** [comment] 2021-09-25 18:05
> With the last committed version I have:
> 
> ```shell
> # autotools
> $ ls -la ./upnp/.libs/libupnp.so* 
> lrwxrwxrwx 1 mroberto users     17 set 25 08:41 ./upnp/.libs/libupnp.so -> libupnp.so.17.1.2
> lrwxrwxrwx 1 mroberto users     17 set 25 08:41 ./upnp/.libs/libupnp.so.17 -> libupnp.so.17.1.2
> -rwxr-xr-x 1 mroberto users 725456 set 25 08:41 ./upnp/.libs/libupnp.so.17.1.2
> -rwxr-xr-x 1 mroberto users 725456 set 25 08:41 ./upnp/.libs/libupnp.so.17.1.2T
> 
> #cmake
> $ ls -la ./build/upnp/libupnp.so*
> lrwxrwxrwx 1 mroberto users     13 set 25 08:40 ./build/upnp/libupnp.so -> libupnp.so.17
> lrwxrwxrwx 1 mroberto users     17 set 25 08:40 ./build/upnp/libupnp.so.17 -> libupnp.so.17.1.2
> -rwxr-xr-x 1 mroberto users 770256 set 25 08:40 ./build/upnp/libupnp.so.17.1.2
> ```
> 
> I don't think we have ever modified the autotools generated scheeme. I don't know if it is even possible to change that.
> 
> > If the top-most symlink (`libupnp.so`) points at the specific .so version (17.1.2) a rebuild is required on each patch level version update of the .so.
> 
> I don't think it has to do with the symlinks. Shouldn't the linker be worried about the soname? Sonames now look right here:
> 
> ```shell
> $ readelf -a ./upnp/.libs/libupnp.so | grep SONAME
>  0x000000000000000e (SONAME)             Library soname: [libupnp.so.17]
> 
> $ readelf -a ./build/upnp/libupnp.so | grep SONAME
>  0x000000000000000e (SONAME)             Library soname: [libupnp.so.17]
> ```
> 
> I am not sure I am understanding correctly what you are saying. We are talking about dynamic links, right? Statically linked programs have an issue only when you deliberately relink them, which is something you should probably do on a new distro release. The dynamic linker has to do its job and "link" every time the program is ran. "Link" means to load the necessary libraries in memory, resolve the symbols and do the necessary fixes to the program's calling addresses. Only the soname should matter and this is a field inside the ELF files. Please correct me, I still don't see why the link order matters.

I was under the impression, that the order of symlinks _has to_ reflect the soname (e.g. "lib.so" -> "SONAME" -> "lib file"). It seems this is actually not the case for all libraries (when glancing across a common lib directory on Linux there are many occurences of "lib.so" -> "lib file" as well).
Sorry for the confusion.

And yes, as long as the soname remains the same, all should be fine for all the software depending on the respective shared libraries and no rebuild is required! :)

**Comment by Vollstrecker** [comment] 2021-09-26 09:41
So
@dvzrv your scripts for packaging won't complain anymore -
@whyman gerbera is buildable -
@mrjimenez you're happy with all versions are written to the several locations, headers and binaries -
\- in the current 1.14 branch? Then we could tag a new release, close this one and hope all that the big problems are solved and stay solved.

And then we all are afraid what comes next.

**Comment by whyman** [comment] 2021-09-26 10:44
Thanks for your efforts @Vollstrecker!

**Comment by mrjimenez** [comment] 2021-09-26 18:05
> So
> @dvzrv your scripts for packaging won't complain anymore -
> @whyman gerbera is buildable -
> @mrjimenez you're happy with all versions are written to the several locations, headers and binaries -
> - in the current 1.14 branch? Then we could tag a new release, close this one and hope all that the big problems are solved and stay solved.
> 
> And then we all are afraid what comes next.

:bat: ooooooo :smile:

**Closed by mrjimenez** 2021-09-26 18:05 UTC

**Comment by mrjimenez** [comment] 2021-09-26 18:08
Hi,

This is a message that I was going to send a few days ago, but got stuck here, there's still something relevant though.

-----

I agree it is somewhat a mess. That basically stems from the fact that the major number in 1.14.11 is "1" and it is currently effectively meaningless.

The formal library version is 1.14.11. On the other hand, the real library version is 17, but that is an internal number that is used in the linking process. The libpnp version should in fact be libpnp-17.11.x, where x means bugfixes only, no API change.

Using the autotools numbering scheeme for external visibility would be very confusing in the cases where we do a backward compatible change. In this case, "current" becomes "18", age would become "1" and the soname would still be libupnp.so.17, since this number is "current - age". Also, two backward compatible changes in the library would set current:age to 19:2, and the next incompatible library version would be 19, not 18, since age resets to zero.

Possible paths I see:
1. Leave things as they are, since we kinda solved it. But it is almost certain that in some point in the future, this will bite us again.
2. Abandon Autotools and use [semantic versioning](https://semver.org/). I don't know if abandoning Autotools is such a good idea, what would be the drawbacks?
3. Something else :smile: 

Regards,
Marcelo.

**Comment by Vollstrecker** [comment] 2021-09-26 21:50
> I agree it is somewhat a mess. That basically stems from the fact that the major number in 1.14.11 is "1" and it is currently effectively meaningless.
The 11 is at least part of the ixml version. My problem is more that we build 2 different libs with with two different versions from a tarball with another different version. Sorting this out wouldn't be easy, as it just doesn't make any sense for a new upnp version when there was an ixml bugfix.

> Using the autotools numbering scheeme for external visibility would be very confusing in the cases where we do a backward compatible change. In this case, "current" becomes "18", age would become "1" and the soname would still be libupnp.so.17, since this number is "current - age". Also, two backward compatible changes in the library would set current:age to 19:2, and the next incompatible library version would be 19, not 18, since age resets to zero.

If I see this correct, this is part of the libtool subset, not autotools at all.

> Possible paths I see:
> 
>     1. Leave things as they are, since we kinda solved it. But it is almost certain that in some point in the future, this will bite us again.

This was first a missunderstood versioning and after that some other confusion only from my side. I didn't check all possible future versions, but atm I'm pretty sure if nothing odd happens when increasing the version, there are not that many points where it can bite us.

>     2. Abandon Autotools and use [semantic versioning](https://semver.org/). I don't know if abandoning Autotools is such a good idea, what would be the drawbacks?

As most auto* based systems I've seen so far are a cruel mixture of auto*, either plain or enchanced with libtool-stuff plus some plain m4 plus some bash, I always vote for dropping this. But I also always want to give time for the maintainers to switch, so at least one more major version with both would be fair. OTOH around half of the time getting the cmake stuff done, was in the part of parsing the auto* stuff, so needing this just a short amount of time would mean a waste of resources. I would say, as long as you can overview everything, it's OK to have them both.

>     3. Something else smile

Like splitting the two libs into separate packages? I guess this would be the cleanest solution, not matter with which tool was used to built them, and no matter what versioning system is used.

**Comment by mrjimenez** [comment] 2021-09-26 22:29
Hi,

Sure, I meant libtool all the time. Sorry for that.

Splitting the libs is ok on my side, but not related to the current issue, as far as I understand.

Libixml seems to be pretty stable, I think we had only one significant issue in the last 20 years, so I really don't see much problem in carrying it along. The bad thing is that if someone wants to use just libixml, today this person must install the full libupnp package. So, +1 to separating the libs.

Just a historical perspective, originally there were three libraries in libupnp: libupnp, libixml and libithreads. Today, the third library has only a fossile appearence and has been replaced by pthreads.
